### ISSUE TITLE
Smileys

### ISSUE THREAD

**Issue by danielle-dlfs** [Julien00859/WebIRC#13]
Bug d'affichage du bouton pour les smileys
http://prntscr.com/a78gtf

**Comment by Julien00859** [comment]
Non reproduit sur Firefox 44.0.2 mais Seb avait le même problème

**Comment by danielle-dlfs** [comment]
Autre probleme avec quelques smileys (j'ai pas testé tous les smileys)
:O donne :)
:P donne :)

**Comment by danielle-dlfs** [comment]
De plus, quand on clique sur le bouton des smileys pour voir ce qu'il y a -> envoie message vide
la fermeture de la fenetre le fait egalement
