### ISSUE TITLE
Add icon

### ISSUE THREAD

**Issue by Ixaoh** [Julien00859/WebIRC#9]
Yup, ça serais nice que sur l'irc "pour faire jolie" qu'il y a des smileys lorsqu'on tape ":D" ou autres, ou bien directement mettre une îcone sur le côter du champ pour écrire

**Comment by Julien00859** [comment]
Done ! :D

**Comment by Julien00859** [comment]
La taille des smileys n'est pas correcte pour les messages (http://puu.sh/ngVZP/daddd52a54.png)
La liste des smileys n'ajoute pas le mot dans la textarea (besoin de lier la fonction addSmiley du scope dans le body html)
